// create references and variables
var searchInput = $('.city-input')
var searchBtn = $('.submit')
var searchHistoryEle = $('.search-history')
var cityDisplayEle = $('.city-display')
var tempDisplay = $('.temp')
var humidityDisplay = $('.humidity')
var windSpeedDisplay = $('.wind-speed')
var uvDisplay = $('.uv-index')
var forecastBoxEle = $('.forecast-box')
var forecastDayOne = $('.day-one')
var forecastDayTwo = $('.day-two')
var forecastDayThree = $('.day-three')
var forecastDayfour = $('.day-four')
var forecastDayfive = $('.day-five')